---
name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./lint
  test-new-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (happy path)
        shell: bash
        run: ./test-new-install --force
      - name: service logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for service
      - name: postgres logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres
      - name: postgres-15 logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres-15
  test-happy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (happy path)
        shell: bash
        run: ./test-migration_ok --force
      - name: service logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for service
      - name: postgres logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres
      - name: postgres-15 logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres-15
  test-no-space-early:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_no-space-destination --force
      - name: service logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for service
      - name: postgres logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres
      - name: postgres-15 logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres-15
  test-no-space-late:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_late-failure --force
      - name: service logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for service
      - name: postgres logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres
      - name: postgres-15 logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres-15
  test-docker-build-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test migration (no space left on target device)
        shell: bash
        run: ./test-migration_docker-build-failure --force
      - name: service logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for service
      - name: postgres logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres
      - name: postgres-15 logs
        if: always()
        continue-on-error: true
        run: ./logs-and-exit-for postgres-15
